name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout
        with:
          fetch-depth: 0
      -
        name: Setup Go
        uses: actions/setup-go
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action
        with:
          distribution: goreleaser
          version: latest
          args release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
